on:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Test and generate coverage
      - uses: 5monkeys/cobertura-action@master
        with:
          path: path/to/coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 30
